# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.gdprBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.gdprBrowser.setMinimumSize(QtCore.QSize(400, 0))
        self.gdprBrowser.setObjectName("gdprBrowser")
        self.horizontalLayout.addWidget(self.gdprBrowser)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.favesTab = QtWidgets.QWidget()
        self.favesTab.setObjectName("favesTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.favesTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.favesTab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.favesTab)
        self.listView.setObjectName("listView")
        self.gridLayout_5.addWidget(self.listView, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.favesTab)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.favesTab, "")
        self.noteTab = QtWidgets.QWidget()
        self.noteTab.setObjectName("noteTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.noteTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.notesBrowser = QtWidgets.QTextBrowser(self.noteTab)
        self.notesBrowser.setObjectName("notesBrowser")
        self.gridLayout_3.addWidget(self.notesBrowser, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.noteTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.noteTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.noteTab, "")
        self.linkedTab = QtWidgets.QWidget()
        self.linkedTab.setObjectName("linkedTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.linkedTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.linkedTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.linkedTab)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_4.addWidget(self.listWidget, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.linkedTab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.linkedTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Add Favourite"))
        self.pushButton_6.setText(_translate("MainWindow", "Remove Favourite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.favesTab), _translate("MainWindow", "Favourites"))
        self.pushButton.setText(_translate("MainWindow", "Add Note"))
        self.pushButton_2.setText(_translate("MainWindow", "Remove Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.noteTab), _translate("MainWindow", "Notes"))
        self.pushButton_3.setText(_translate("MainWindow", "Add Link"))
        self.pushButton_4.setText(_translate("MainWindow", "Remove Link"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linkedTab), _translate("MainWindow", "Linked"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

