# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.gdprBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.gdprBrowser.setMinimumSize(QtCore.QSize(400, 0))
        self.gdprBrowser.setObjectName("gdprBrowser")
        self.horizontalLayout.addWidget(self.gdprBrowser)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.notesTab = QtWidgets.QWidget()
        self.notesTab.setObjectName("notesTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.notesTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.anoteButton = QtWidgets.QPushButton(self.notesTab)
        self.anoteButton.setObjectName("anoteButton")
        self.gridLayout_5.addWidget(self.anoteButton, 2, 0, 1, 1)
        self.rnoteButton = QtWidgets.QPushButton(self.notesTab)
        self.rnoteButton.setObjectName("rnoteButton")
        self.gridLayout_5.addWidget(self.rnoteButton, 3, 0, 1, 1)
        self.notePad = QtWidgets.QPlainTextEdit(self.notesTab)
        self.notePad.setObjectName("notePad")
        self.gridLayout_5.addWidget(self.notePad, 1, 0, 1, 1)
        self.noteBrowser = QtWidgets.QTextBrowser(self.notesTab)
        self.noteBrowser.setObjectName("noteBrowser")
        self.gridLayout_5.addWidget(self.noteBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.notesTab, "")
        self.linksTab = QtWidgets.QWidget()
        self.linksTab.setObjectName("linksTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.linksTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.linkBrowser = QtWidgets.QTextBrowser(self.linksTab)
        self.linkBrowser.setObjectName("linkBrowser")
        self.gridLayout_3.addWidget(self.linkBrowser, 0, 0, 1, 1)
        self.alinkButton = QtWidgets.QPushButton(self.linksTab)
        self.alinkButton.setObjectName("alinkButton")
        self.gridLayout_3.addWidget(self.alinkButton, 1, 0, 1, 1)
        self.rlinkButton = QtWidgets.QPushButton(self.linksTab)
        self.rlinkButton.setObjectName("rlinkButton")
        self.gridLayout_3.addWidget(self.rlinkButton, 2, 0, 1, 1)
        self.tabWidget.addTab(self.linksTab, "")
        self.favesTab = QtWidgets.QWidget()
        self.favesTab.setObjectName("favesTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.favesTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rfaveButton = QtWidgets.QPushButton(self.favesTab)
        self.rfaveButton.setObjectName("rfaveButton")
        self.gridLayout_4.addWidget(self.rfaveButton, 2, 0, 1, 1)
        self.afaveButton = QtWidgets.QPushButton(self.favesTab)
        self.afaveButton.setObjectName("afaveButton")
        self.gridLayout_4.addWidget(self.afaveButton, 1, 0, 1, 1)
        self.faveBrowser = QtWidgets.QTextBrowser(self.favesTab)
        self.faveBrowser.setObjectName("faveBrowser")
        self.gridLayout_4.addWidget(self.faveBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.favesTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.anoteButton.setText(_translate("MainWindow", "Add"))
        self.rnoteButton.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notesTab), _translate("MainWindow", "Notes"))
        self.alinkButton.setText(_translate("MainWindow", "Add"))
        self.rlinkButton.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linksTab), _translate("MainWindow", "Linked"))
        self.rfaveButton.setText(_translate("MainWindow", "Remove"))
        self.afaveButton.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.favesTab), _translate("MainWindow", "Favourites"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

